name: PublishDesoProtocol

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - name: Build
      #    run: npm run build
      # - name: Build
      #    run: npm run build
      - name: Format
        run: npm run format
      - name: Publish
        uses: ./.github/workflows/actions/publish-protocol
        # with:
        #   example-param: Hello World
