name: PublishDesoProtocol

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: CI
        run: npm ci --force
      - name: Format
        run: npm run format
      - name: Patch
        run: npm version patch
        working-directory: ./libs/deso-protocol
      - name: Build
        run: npx nx run deso-protocol:build
        # working-directory: ./libs/deso-protocol
      - name: Publish
        run: npm publish
        working-directory: ./dist/libs/deso-protocol
