name: PublishDesoProtocol
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          # registry-url: 'https://registry.npmjs.org/'
      - name: CI
        run: npm ci --force
      - name: Format
        run: npm run format
      - name: Patch
        run: npm version patch
        working-directory: ./libs/deso-protocol
      - name: Build
        run: npx nx run deso-protocol:build
        # TODO: Seems to be an issue with github right now where its not reading the secret.
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_AUTH_TOKEN }}
      #     package: ./libs/deso-protocol/package.json
