name: 'publish'
description: 'Deploys a patch anytime the library is updated'
author: 'Tyler Fischer'

runs:
  using: 'node12'
  main: '.github/scripts/publish.js'

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
