name: PublishDesoProtocol

on:
  push:
    branches:
      - jackson/test-workflow
    paths:
      - "libs/deso-protocol/**"
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - name: Setup
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npm ci
      - name: NPM Publish
        run: bash ./scripts/bump_package_version.sh deso-protocol
