name: PublishDesoProtocol

on:
  push:
    branches:
      - master
    paths:
      - "libs/deso-protocol/**"
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - name: "NPM Publish"
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          COMMIT_TYPE=`git log -1 --pretty=format:"%s" | cut -d: -f1`
          echo "Commit type: $COMMIT_TYPE"
          npm ci

          cd libs/deso-protocol

          if [[ -n `git log -1 | grep "BREAKING_CHANGE"` ]]; then
            npm version major
          elif [[ $COMMIT_TYPE == 'feat' ]]; then
            npm version minor
          elif [[ $COMMIT_TYPE == 'fix' ]]; then
            npm version patch
          else
            echo "Could not infer new version from commit message."
            exit 1
          fi

          cd -
          npx nx run deso-protocol:build
          cd dist/libs/deso-protocol

          echo "Publishing new version"
          npm version
          npm publish --access public
          cd -
      - name: "Auto commit Version Bump"
        run: |
          git add libs/deso-protocol/package.json
          git commit -m "ci: automated release version bump"
          git push origin HEAD:master
