name: PublishDesoProtocol

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: CI
        run: npm ci --force
      - name: Format
        run: npm run format
      - name: Patch
        run: npm version patch
        working-directory: ./libs/deso-protocol
      - name: Build
        run: npx nx run deso-protocol:build
      - name: Publish
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        working-directory: ./dist/libs/deso-protocol
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
